### ISSUE TITLE
hard coded host address in the error message

### ISSUE THREAD

**Issue by jmikerq** [yoctopuce-examples/node-red-contrib-yoctopuce-sensors#1]
You have a hard coded error msg in the yoctopuce-sensor.js file, line 40:

```node.error('Cannot contact VirtualHub on 127.0.0.1: ' + errmsg.msg);```

I think this would make debugging confusing when connecting to a different host address.

**Comment by yoctopuce** [comment]
Fixed in version 1.0.5 (94fc5befc06e01dfe0d0be4096fc8617fac1ea51)
